version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db-authentication
    environment:
      POSTGRES_DB: authentication_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ADMIN
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: